<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Email_field</name>
   <tag></tag>
   <elementGuidId>4a51e0b0-7061-4c40-b82c-a88177e25fa2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//android.widget.EditText[@content-desc=&quot;input-email&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//android.widget.EditText[@content-desc=&quot;input-email&quot;]</value>
      <webElementGuid>51759687-1658-4d4e-817e-18ede151b3e4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
